FROM ubuntu:18.04
LABEL maintainer="Pranav Bhatt(adpranavb2000@gmail.com)"

RUN set -ex; \
  apt-get update -y; \
  apt-get install -y snapd
  DEBIAN_FRONTEND=noninteractive snap install bcc;

COPY entrypoint.sh /
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["/bin/bash"]
